Pictures for index and new catalogue
aleksandermikhailov/Nerds pull request #3
Opened 2020-04-03 08:08 UTC by aleksandermikhailov

Added some pictures to index.html and created catalogue.html

2020-04-03 17:02 UTC, mrnptrv requested changes
Пожалуйста, посмотри внимательно комментарии и исправь неточности :)

2020-04-03 17:02 UTC, mrnptrv commented on index.html
>      <div class="slider">
Заголовок "Описание студии", проверь закрывающий тег, он не совпадает с открывающим

2020-04-03 17:02 UTC, mrnptrv commented on index.html
>      <footer class="page-footer">
(Не могу добавлять комменты к строчкам, которые не менялись, поэтому скидываю всё сюда))
1. Тип кнопок "Заказать" должен быть button, а type="submit" используется для отправки заполненных форм.
2. Этим кнопкам — или целым айтемам — нужно будет добавить какие-то модификаторы, потому что кнопки отличаются по цвету. Можно добавить дополнительные классы, так же как ты добавил картинкам в портфолио (portfolio-pink и всё такое).
3. Жирные строчки в теге <b> не нужно заключать в <p> (это в нескольких местах), не пугайся, если они в одну строку лезут со всем остальным, стилями будем править :)

А ещё. Секции services и features придётся заключить ещё в один контейнер, это нужно будет для удобства вёрстки на флексах, но пока ничего не делай, просто имей в виду.

2020-04-03 17:02 UTC, mrnptrv commented on index.html
>          <p>191186, Санкт-Петербург, <br>ул. Б. Конюшенная, д. 19/8 <br>тел. +7 (812) 275-75-75</p>
Кнопке ниже не хватает типа (type="button")

2020-04-03 17:02 UTC, marinakuznetcova commented on index.html
>          <textarea id="user-letter" rows="20" cols="100" placeholder="В свободной форме"></textarea>
7. Лейблам и инпутам тоже нужны классы, я обычно не парюсь и так и называю, form-input / form-label.
8. У поля с почтой должен быть соответствующий тип type="email"

2020-04-04 13:53 UTC, aleksandermikhailov commented on index.html
>      <footer class="page-footer">
Done! :)

2020-04-06 17:40 UTC, mrnptrv approved these changes

2020-04-06 17:40 UTC, mrnptrv commented on catalogue.html
> +        <li><a href="shop.html" title="Магазин">Магазин</a></li>
Здесь есть активный элемент списка — пункт "Магазин" выделен подчёркиванием, соответственно, нам нужно будет как-то иначе его стилизовать. Поэтому этой ссылке нужен специальный класс. Например, selected или active.

2020-04-06 17:40 UTC, marinakuznetcova commented on catalogue.html
> +        <input type="range" min="0" max="15000">
Пока не уверена, что мы будем делать со строчкой, где "ОТ" и "ДО", посмотрим. В идеале нужно выводить туда значения автоматом. То есть когда крутишь ручку, значения меняются. Но это JS нужен, поэтому давай пока просто сверстаем эту строчку. Туда нужно бахнуть спаны с "ОТ" и "ДО", а цифры заключи в <output>.

А ещё 15000 ведь не максимальное значение, а текущее. Пока можешь добавить ему атрибут value со значением 15000, а максимальное увеличить до 20000 или около того, на глаз.

2020-04-06 17:40 UTC, marinakuznetcova commented on catalogue.html
> +  <input type="submit" class="btn" value="Показать">
Хм, а почему input, а не button? Можно и так, просто интересно.

2020-04-06 17:40 UTC, marinakuznetcova commented on index.html
> +          <button class="btn order-btn" type="button">Заказать</button>
Насчёт кнопок, я имела в виду разные модифицирующие классы, чтобы им потом разные цвета присваивать. Например, class="order-btn order-btn-green" :)

2020-04-06 17:40 UTC, marinakuznetcova commented on catalogue.html
> +          <li><a class="social-btn-vk" title="vk">Вконтакте</a></li>
Я кажется где-то писала (или только думала), что этим кнопкам соцсетей нужны модификаторы типа `class="social-btn social-btn-vk"`. То есть, должен быть общий класс, который будет описывать общие для них вещи (размеры, круглость, отступы, позицию фона...), и плюс для каждой кнопки свой, который будет добавлять уникальную картинку на фон.

2020-04-06 17:41 UTC, merged